### PR TITLE
Assignment 2 Network Analysis: igraph for discipline data

### PR DESCRIPTION
**Pull request by charlottewoo**
Created a Fruchterman Reingold graph based on discipline data.

### CODE REVIEW

**Comment by charles-lang** [comment]
Hi Charlotte, this looks great. You seem to have a handle on how to build a graph and manipulate its characteristics. With respect to Zotero, in 4050 I make the students keep their own documentation of the techniques they learn and they store their notes in Zotero. It is a good idea to do that somewhere, though you may prefer different software.

**Comment by charlottewoo** [comment]
Hi Charles, thanks a lot for your feedback.  Regarding Zotero, I was very impressed by its functionalities. I started off building my research database on EndNotes (I did not know about Zotero at the time, and just downloaded EndNotes from TC's student portal and started using it since) and did not look around for an alternative. Now that I've seen Zotero, I may start using it instead as it has some really great features such as clipping off a webpage and inserting references in a Word document.  I do need to figure out how to migrate my data from EndNotes to Zotero though.  Anyhow, thanks for introducing Zotero to me.

**Comment by charles-lang** [comment]
No worries, hope you find it useful. You should be able to import pretty easily - in the worst case scenario export your bib from Endnote as BibTex. Good luck!

On Thu, Feb 09, 2017 at 3:53 PM Charlotte Woo

<
mailto:Charlotte Woo <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

Hi Charles, thanks a lot for your feedback. Regarding Zotero, I was very impressed by its functionalities. I started off building my research database on EndNotes (I did not know about Zotero at the time, and just downloaded EndNotes from TC's student portal and started using it since) and did not look around for an alternative. Now that I've seen Zotero, I may start using it instead as it has some really great features such as clipping off a webpage and inserting references in a Word document. I do need to figure out how to migrate my data from EndNotes to Zotero though. Anyhow, thanks for introducing Zotero to me.

—

You are receiving this because you commented.

Reply to this email directly,
https://github.com/core-methods-in-edm/assignment2/pull/27#issuecomment-278770386
, or

**Comment by charlottewoo** [comment]
You are right, Charles.  Looks like BibTex and RIS are the recommended standards, although they do have a note that specifically talks about EndNote migration using RIS.  It looks promising!

**Pull request closed without merging**
